# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jtarpley/ubuntu2404_base"
  config.vm.guest = :ubuntu # Explicitly set guest OS

N = 3
(1..N).each do |machine_id|
  config.vm.define "machine#{machine_id}" do |machine|
    machine.vm.hostname = "machine#{machine_id}"
    machine.vm.box_check_update = false
    machine.vm.network "private_network", ip: "192.168.77.#{10+machine_id}"
    
    machine.vm.provision "shell", inline: "sudo ufw allow 80/tcp"

      machine.vm.provider "libvirt" do |libvirt|
        libvirt.memory = 2048
        libvirt.cpus = 2
        libvirt.random_hostname = false

        libvirt.storage_pool_name = "default"
        libvirt.machine_virtual_size = 10

      end

      if machine_id == 1
         machine.vm.provision :ansible do |ansible|
           ansible.inventory_path = "inventory.ini"
           ansible.playbook = "playbook_machine1.yml"
         end
      else
         machine.vm.provision :ansible do |ansible|
           ansible.inventory_path = "inventory.ini"
           ansible.playbook = "playbook.yml"
         end
      end
    end
  end
end
