# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jtarpley/ubuntu2404_base"
  config.vm.guest = :ubuntu 

  config.vm.define "machine1" do |machine|
    machine.vm.hostname = "machine1"
    machine.vm.box_check_update = false
    machine.vm.network "private_network", ip: "192.168.77.11"
    
    machine.vm.provision "shell", inline: "sudo ufw allow 80/tcp"
    machine.vm.provision "shell", inline: "sudo ufw allow 443/tcp"

      machine.vm.provider "libvirt" do |libvirt|
        libvirt.memory = 2048
        libvirt.cpus = 2
        libvirt.random_hostname = false

        libvirt.storage_pool_name = "default"
        libvirt.machine_virtual_size = 10

      end

         machine.vm.provision :ansible do |ansible|

           ansible.playbook = "playbook_machine1.yml"
           ansible.host_key_checking = false
           ansible.vault_password_file = ".vault_password"
      end
  end
end
